### ISSUE TITLE
Support moving dashboard UI out of the apiserver to a separate pod

### ISSUE THREAD

**Issue by ohohoreilly** [kubernetes/kube-ui#1]
Support https://github.com/GoogleCloudPlatform/kubernetes/pull/10077

**Comment by bcbroussard** [comment]
@preillyme I'll take a look and see what we need to do to transition

**Comment by ohohoreilly** [comment]
@bcbroussard `docker run -p 8080:8080 gcr.io/kube-ui/kube-ui` I've push a dummy container for now. Also probably worth connecting with @timstclair as well.

**Comment by timstclair** [comment]
I'm getting a permission error when I try to run that command:

```
$ docker run -p 8080:8080 gcr.io/kube-ui/kube-ui
exec: "/kube-ui": permission denied
Error response from daemon: Cannot start container cd794c072d6d560748e36f3a355fb4ada42c9e23f21a713a6b103f6afcd0ced1: [8] System error: exec: "/kube-ui": permission denied
```

**Comment by ohohoreilly** [comment]
@timstclair yeah that's normal for now. It's just a dummy container. @bcbroussard is going to fix it tonight. Thanks for checking it out. I used your Docker file for it as well: https://github.com/timstclair/kubernetes/blob/ui-server/cluster/addons/kube-ui/image/Dockerfile

**Comment by timstclair** [comment]
Cool, thanks for doing this. I'll test it out tomorrow, and update https://github.com/GoogleCloudPlatform/kubernetes/pull/10077 to point to that image if it works.
