### ISSUE TITLE
Proposal: Kube-UI to have the debug/pprof/ related information

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/kube-ui#15]
It will be great to have the debug/pprof related information in the kube-ui as default instead by a parameter when you launch the kube-apiserver.

**Comment by ohohoreilly** [comment]
@kgrvamsi well it's a slight inconvenience is that APIserver uses default server for intra-cluster communication, so plugging profiler to it is not really useful. Can you explain a bit more about what you're thinking?

Are you wanting to use: `go tool pprof` with it as well?

**Comment by kgrvamsi** [comment]
infact lets take i'm hosting the cluster at client site and i need to understand the problems happening at a high level infact like the threads opened byt the apiserver and other factors to know the memory process of the Apiserver in handling the things and if this infact based upon the output from the profiler if there are some graphs which shows us in the UI it will be of great help where the API server it self can be a collection of everything for any sort of cluster installations to do either at client site or at a region level.
