### ISSUE TITLE
Release a new kube-ui version (w/ reverse proxy support)

### ISSUE THREAD

**Issue by karlkfi** [kubernetes/kube-ui#23]
We (Mesosphere) would like a new kube-ui release to be published (to GCR or dockerhub), now that #19 has been merged. Then we can package an official version with our next DCOS Kubernetes v1.x package, rather than publishing our own fork.

We should probably also figure out access control so that non-google committers can be given access to publish.

**Comment by karlkfi** [comment]
Discoverability of GCR image versions is rather poor. We should consider using github releases that link to GCR and/or [dockerhub automated builds](https://docs.docker.com/docker-hub/github/).

**Comment by mikedanese** [comment]
I can prepare a release. We switched from https://hub.docker.com/r/kubernetes/ to https://gcr.io because gcr was significantly faster (but this was before docker registry v2).

**Comment by karlkfi** [comment]
That's a reasonable reason. Do we know if dockerhub v2 is any faster? 
I've anecdotally noticed more images have parallel download now, but I'm not sure what the qualification for that is.

I think using git release branches with descriptions on github's releases page would be an easy win.

I don't know how access control works on GCR, but I know on dockerhub we could have a k8s or kube-ui org with push rights for members.

**Comment by ohohoreilly** [comment]
@karlkfi we'll need someone with access to `gcr.io/google_containers` to push the new container.

**Comment by ohohoreilly** [comment]
Thanks @mikedanese

**Comment by mikedanese** [comment]
I'm going to do this sometime today.

As far as discovery, I know it's terrible. We've discussed this. You can use

```
docker search gcr.io/google_containers
```

or

```
gsutil ls gs://artifacts.google-containers.appspot.com/containers/repositories/library/ 
```

to list repositories and you can use:

```
gsutil ls gs://artifacts.google-containers.appspot.com/containers/repositories/library/<image-name>
gsutil ls gs://artifacts.google-containers.appspot.com/containers/repositories/library/kube-ui
```

to discover tags. There is also a rest api if you don't like gsutil. It might also be possible to use the docker registry api to do the same thing but I haven't tried. (I realize this is not a great answer but it's something).

**Comment by mikedanese** [comment]
If you haven't noticed I pushed v2 today. See #27 and kubernetes/kubernetes#13274. If you are happy with the build please LGTM. @timstclair we have e2e tests for this, right?

**Comment by timstclair** [comment]
The [kube-ui e2e test](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/kube-ui.go) just tests that the kube-ui is started correctly and responds with a 200. I don't know whether the actual [UI tests](https://github.com/kubernetes/kube-ui#testing) are run automatically.

**Comment by sttts** [comment]
I have tested the v2 image behind a nginx reverse proxy, resembling the setup we have in DCOS. Everything looks fine.

lgtm.
