### ISSUE TITLE
Pod Visualizer

### ISSUE THREAD

**Issue by Chive** [kubernetes/kube-ui#25]
On my search of finding something to visually represent my cluster (as seen in [archive.org](https://archive.org/details/EuroPython_2015_If1QdBJA) at ~51 minutes), I found the undocumented **Pod Visualizer** in [`manifest.json`](https://github.com/kubernetes/kube-ui/blob/master/master/components/dashboard/manifest.json#L14-L18).

The whole GUI is working perfectly except for that view - I guess that's why it's not linked / documented anywhere?

![screen shot 2015-08-25 at 21 34 15](https://cloud.githubusercontent.com/assets/2700360/9483714/1305a102-4b71-11e5-9236-c4b4a2896b5e.png)

**Comment by ohohoreilly** [comment]
@bcbroussard what was the goal with this one?

**Comment by bcbroussard** [comment]
@preillyme This was an early prototype which was abandoned in favor of the pod listing page and dashboard bar gauge ui. It visually grouped pods together into a multi-colored, multi-sized block representing the makeup of each server.

The code can be removed from the manifest.

**Comment by ohohoreilly** [comment]
Okay thanks @bcbroussard
