### ISSUE TITLE
Enable auth when supporting for multiple namespace

### ISSUE THREAD

**Issue by dalanlan** [kubernetes/kube-ui#26]
Since apiserver supports authorization, it should be more reasonable that a user can only access (read) the pods within his authority. Users could bypass the auth check via kube-ui otherwise.

See [authorization.md](https://github.com/kubernetes/kubernetes/blob/master/docs/admin/authorization.md#examples) for more details. 
Kinda related to #5 
/cc @preillyme

**Comment by ohohoreilly** [comment]
Makes total sense @dalanlan and we're taking that approach on https://github.com/kubernetes/kube-ui/issues/5 thanks for opening the issue.
