### ISSUE TITLE
Add num cpus to dashboard showing nodes

### ISSUE THREAD

**Issue by nickithewatt** [kubernetes/kube-ui#29]
This is not so much a bug as a minor feature request to add the number of CPUs to the visual dashboard showing the nodes. The information is already available when looking at the individual nodes themselves. 
Granted there is no dynamic visual aspect to this information, but it is still handy to be able to see from this view without having to click into the node details itself.

**Comment by stevesloka** [comment]
@nickithewatt The cpus has been added and merged!

**Comment by sebholstein** [comment]
Done. See #39
