### ISSUE TITLE
Fix README for new repo

### ISSUE THREAD

**Issue by ohohoreilly** [kubernetes/kube-ui#3]
We need to fix the README file for the new repo location.

**Comment by luxas** [comment]
Is this going to be fixed soon?
Provide an easy way to setup this service, please.

I was able to get it up and running, via downloaded source code and `kubelet proxy --www=app --www-prefix=/ --accept-hosts=""`

But now it doesn't find `/api/v1/proxy/nodes/192.168.1.59:4194/api/v1.0/containers/`
Is it the right url to request?

Should I create a new issue?
I will probably contribute something to this, at least I will try to make a UI for myself

**Comment by tsl0922** [comment]
@luxas Remove `--accept-hosts=""` and ensure you are running this command at the root of the kube-ui folder, I have a fix for the `docs/ui.md`, see #31

**Comment by sebholstein** [comment]
Fixed with #31.
