### ISSUE TITLE
kube-ui support management operations

### ISSUE THREAD

**Issue by linzichang** [kubernetes/kube-ui#32]
Now the kube-ui can just "displays". I think it's better to provide the "management" such as create, delete. Are there any plans about this ?

**Comment by sebholstein** [comment]
@linzichang yes, this is No. 1 on my todo list. Will split this into multiple feature issues shortly. I should have something in the next few weeks.

**Comment by linzichang** [comment]
@SebastianM Looking forward to see your todo list. Maybe I can help on those features.

**Comment by stevesloka** [comment]
@SebastianM Do you have some thing in progress? I can look to help out as well, don't want to start something if you already have wip.

**Comment by sebholstein** [comment]
Hey @linzichang & @stevesloka, sorry for the late answer. I was on vacation, so I couldn't answer earlier.

I've made some big changes to the project structure that are in discussion right now. When this finished, there would definitely be a lot of tasks where you could help out. I will inform you when I have something new to share.

**Comment by stevesloka** [comment]
@SebastianM sounds good, let me know as soon as you have something, I'd love to jump in and add some more things! If you are making such big changes, I hate to keep rolling forward with the current code.
