### ISSUE TITLE
Sort fileSsytemData by device

### ISSUE THREAD

**Issue by so0k** [kubernetes/kube-ui#33]
The Dashboard FileSystems change order all the time, is it possible to sort this array by the device and keep the order consistent across updates or is the order random on purpose?

see https://github.com/kubernetes/kube-ui/blob/master/master/shared/js/modules/services/cAdvisor.js#L126

``` javascript
var f = {
    device: data.device,
    filesystemNumber: i + 1,
    usage: data.usage,
    usageDescription: humanizeMetric(data.usage),
    capacity: data.capacity,
    capacityDescription: humanizeMetric(data.capacity),
    totalUsage: Math.floor((data.usage * 100.0) / data.capacity)
};

filesystemData.push(f);
```

I'd try to make the change and send a pull request, but my angular is rusty...

**Comment by sebholstein** [comment]
@so0k Ping me if you need help.

**Comment by packetcollision** [comment]
:+1: the Dashboard file system rings are basically useless on CoreOS, because of the jumping.

It would be even nicer if they showed up as the actual device/mount names, but I assume that should be a different ticket.

**Comment by manojlds** [comment]
+1 for this.

**Comment by ohohoreilly** [comment]
+1
