### ISSUE TITLE
How to add a component to a default install?

### ISSUE THREAD

**Issue by sheriffmohamed** [kubernetes/kube-ui#41]
Hi,

I just got kubernetes up and running and noticed that the [graph](https://github.com/kubernetes-ui/graph) component isn't in the default installation. Is there some documentation on how to add this or any component to a default installation?

Thanks!

**Comment by ohohoreilly** [comment]
Hello @sheriffmohamed @jackgr is working on documenting the steps needed.

**Comment by sheriffmohamed** [comment]
Great! Thank you. @jackgr I'm assuming the steps are still being worked on?
