### ISSUE TITLE
Support for multiple namespaces

### ISSUE THREAD

**Issue by stensonb** [kubernetes/kube-ui#5]
Currently, the UI only supports the "default" namespace...we should display all namespaces the current user has access to...

Care on which namespaces to display should be integrated with UI user authorization (some users may not have access to all namespaces -- though, this should probably be enforced at the API level, if it isn't already)

**Comment by ohohoreilly** [comment]
@stensonb thanks for creating this issue. We'd welcome your PR as well. It's currently on the roadmap to support this feature.

**Comment by stensonb** [comment]
How does this project relate to the UI stuff found here: https://github.com/GoogleCloudPlatform/kubernetes

**Comment by ohohoreilly** [comment]
@stensonb I'm trying to move the www code out of the main repo and in to this one. We'll then publish the container from here.

**Comment by stensonb** [comment]
Ok, cool...I'll submit PRs here then. :)

**Comment by ohohoreilly** [comment]
@stensonb are you working on a PR for this feature?

**Comment by stensonb** [comment]
I had hoped to, but I don't have time now...maybe in a few weeks...

**Comment by ohohoreilly** [comment]
@stensonb okay, I'll take a look at fixing it then. Thanks for the feedback.

**Comment by nickithewatt** [comment]
+1

**Comment by ohohoreilly** [comment]
@nickithewatt I should have something in this week.

**Comment by nickithewatt** [comment]
fantastic, looking forward to it!

**Comment by Smana** [comment]
+1

**Comment by timcrider** [comment]
+1

**Comment by opskumu** [comment]
+1

**Comment by stevesloka** [comment]
I can help with this, do you think we just show all (e.g. --all-namespaces=true) or provide some sort of selector dropdown?

**Comment by Smana** [comment]
Any news on this issue please ?

**Comment by stevesloka** [comment]
@Smana I did the work and it was merged last night. I'm not sure the process to cut a new image, but you could build yourself. I'm interested to see if it works out for you.

**Comment by timcrider** [comment]
@stevesloka I think all-namespaces by default, with the option to limit based on a specific namespace would suit my needs perfectly.

**Comment by stevesloka** [comment]
@timcrider That's what I did for now, so the head of master should show all namespaces by default. I added "Namespace" column to each of the views and detail pages. I thought the next step would be to filter by permissions or allow to filter manually (which are mentioned in other Issues).

**Comment by Smana** [comment]
Hello, on my cluster the kube-ui is deployed with by kubernetes itself with the following image

```
gcr.io/google_containers/kube-ui:v1.1
```

How can i have the "multiple namespaces" support, i don't know who's the maintainer of this image.
Is there another registry from which I can pull the latest image supporting this feature ?

Thanks

**Comment by stevesloka** [comment]
I'm not sure how the images get cut, @preillyme ?

**Comment by ohohoreilly** [comment]
@stevesloka we can ask @mikedanese to cut a new one.

**Comment by mikedanese** [comment]
@preillyme @stevesloka and anyone else, `gcr.io/google_containers/kube-ui:v3` is pushed. Please validate

**Comment by Smana** [comment]
@mikedanese Hello and thank you.
I just tested your image and i can't see any way to change/display namespaces.
my replication controller is configured as follows : 

```
kubectl describe rc --namespace=kube-system kube-ui-v3
Name:       kube-ui-v3
Namespace:  kube-system
Image(s):   gcr.io/google_containers/kube-ui:v3
Selector:   k8s-app=kube-ui,version=v1
Labels:     k8s-app=kube-ui,kubernetes.io/cluster-service=true,version=v3
Replicas:   1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

I've checked that the right image have been pulled (on the node hostiing the pod): 

```
docker ps | grep kube-ui
48973fe13b42        gcr.io/google_containers/kube-ui:v3              "/kube-ui"               2 minutes ago       Up 2 minutes                            k8s_kube-ui.6395ed62_kube-ui-v3-hxy9m_kube-system_3d76cf97-6cce-11e5-9de2-525400a454df_940513de
```

Am i mistaken somewhere ?

**Comment by Smana** [comment]
For info my cluster is built with this : https://github.com/ansibl8s/k8s-cluster

**Comment by genti-t** [comment]
I just tested kube-ui-v3 and at the moment i see the nodes, pods, rc, services but no dashboard.
The "Dashboard Views" with the "Node Resource Usage" is blank.
here is my rc:

```
kubectl describe rc --namespace=kube-system kube-ui-v3
Name:       kube-ui-v3
Namespace:  kube-system
Image(s):   gcr.io/google_containers/kube-ui:v3
Selector:   k8s-app=kube-ui,version=v3
Labels:     k8s-app=kube-ui,kubernetes.io/cluster-service=true,version=v3 
Replicas:   1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
```

**Comment by genti-t** [comment]
Find the issue, The official documentation from CoreOS, make kubelet run with:

```
--cadvisor-port=0 
```

generating an empty dashboard on UI.

Thank you

**Comment by dalanlan** [comment]
@genti-t Had no experience with kube-ui-v3, yet i was wondering why we should set `--cadvisor-port` to 0. Is there any conflict situation with default 4194?

**Comment by stevesloka** [comment]
@Smana You should see all namespaces now, before you only saw the "default" namespace. There's no way to filter or select a namespace now.

**Comment by genti-t** [comment]
@dalanlan I had no reason tu use --cadvisor-port=0, the default is fine for me. That was a misguide.

**Comment by Smana** [comment]
yes ! that's ok for me it works :) thanks

**Comment by dalanlan** [comment]
@genti-t  Thanks for the clarification.

**Comment by mikedanese** [comment]
I believe this is complete.
