### ISSUE TITLE
nodes marked NotReady prevent "normal" display of the dashboard

### ISSUE THREAD

**Issue by stensonb** [kubernetes/kube-ui#6]
I need to prove this empirically, but it looks like any node marked "NotReady" breaks the display of the dashboard...

I had some nodes I had deleted, but failed to remove via "kubectl delete node my_old_node_name"...and the dashboard was displaying the header, but no data about each of the "Ready" nodes.

After running the "kubectl delete node my_old_node_name", the dashboard started displaying node data (cpu, memory) again...

**Comment by stensonb** [comment]
I expect "NotReady" nodes to NOT break the display of "Ready" nodes.

Furthermore, it might be nice to visually sort/display/delineate nodes by Status (Ready, NotReady, other statii I don't know about, etc)...

**Comment by ohohoreilly** [comment]
@stensonb thanks for the bug report I'll take a look and test shortly. Sorry for the delay in responding.

**Comment by stevesloka** [comment]
@stensonb This issue should be resolved now with PR #37

**Comment by roberthbailey** [comment]
Can this be closed?

**Comment by ohohoreilly** [comment]
@roberthbailey yes.
