### ISSUE TITLE
Migrating to github org kubernetes

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kube-ui#7]
Over the next few weeks, we are planning on migrating kubernetes, heapster, and cadvisor to the new org https://github.com/kubernetes as part of transferring ownership of kubernetes to CNCF. Would we like to transfer any kubernetes-ui repos as well? Opening this issue to discuss.

@preillyme @jackgr @bgrant0607

Downstream tracking issue GoogleCloudPlatform/kubernetes#12211

**Comment by ohohoreilly** [comment]
@mikedanese makes sense to me. We should move the repo under kubernetes-ui for sure.

**Comment by mikedanese** [comment]
Ya, let's start with kube-ui. It would be nice to consolidate kubedash, kube-ui, and kube-ui-docker into a single repo. That should make release and e2e testing simpler. Are the other repos in this organization libraries that are published somewhere?

I've created a kube-ui team in the kubernetes org and invited you. Let me know who else to invite and when you want to make the transfer.

**Comment by ohohoreilly** [comment]
@mikedanese so should we fork https://github.com/kubernetes-ui/kube-ui to https://github.com/kubernetes/kube-ui?

**Comment by mikedanese** [comment]
@preillyme forks are not indexed by github so search won't work for them. I think it would be better to transfer.

**Comment by ohohoreilly** [comment]
@mikedanese okay so would you like to create the new repo and do a bare clone of the old one?

**Comment by mikedanese** [comment]
@preillyme can you ping me on irc to discuss?

**Comment by ohohoreilly** [comment]
@mikedanese I'll ping you on IRC after lunch.

**Comment by ohohoreilly** [comment]
@mikedanese I'm going to close this issue as I think it's resolved now with the move.

**Comment by mikedanese** [comment]
:+1: !!!
